### ISSUE TITLE
Stop hard-coding e-mail addresses in the HTML page templates

### ISSUE THREAD

**Issue by popescuv** [ELDAELRA/ELRI#36]
Instead, contact e-mail addresses should be defined as variables in the local_settings and customised for each deployment as one sees fit.

**Comment by tetchegoyhen** [comment]
The mechanism is in place on the FCUL branch to stop hard-coding email addresses and we will close the issue once we merge with the MASTER. We still need to double-check that all current hard-coded references have been replaced, is this correct?

**Comment by luismsgomes** [comment]
I have replaced all occurrences that I have found in the templates and also replaced the PO files I did not recompile the translations, however.

In principle, it should be enough to recompile the translations and commit the recompiled versions.

A brief note about the solution implemented:
Instead of replacing the email with a simple variable replacement such as {{ email }} I have created a template tag.
This solution was needed because for the 404.html and 500.html templates we have no control of the context that is passed to render these templates.  Thus, we could not add a variable containing the emails.
