### ISSUE TITLE
Enforce https protocol in user Registration and Authentication

### ISSUE THREAD

**Issue by emartinezvic** [ELDAELRA/ELRI#45]
Connection is not currently secure by default.

**Comment by gpfconway** [comment]
Hi Eva - Gary Conway from the Irish ELRI team here. 
Shouldn't the whole site should be delivered over HTTPS? not just User Reg.
This shoud be trivial to do with Django and self-signed certs. We have our own wildcard SSL certs here we could use for this.

**Comment by jcorteslinkare** [comment]
Hi Gary/Eva,

Sorry to break in, but in this matter i can suggest that customers use existent load balancer that can SSL offload to the Nginx server image (so that internally the docker containers communicate with less overhead, as SSL communication brings more overhead comparing to plain communication, you can check this article http://techgenix.com/ssl-acceleration-offloading-security-implications/).

If this does not fit the purposes (no load balancer is going to be used, only DNS direct) i think that even the nginx server can fit the purpose of SSL offloading (i am more used to apache httpd configurations but i think that with some investigation it can be achieved).

This way we can reduce the overhead to the django application and let the security handling up to the load balancer or nginx servers, is this valid for you?

**Comment by gpfconway** [comment]
Hi João,
Ok. That is something I can test here, and will post results.

**Comment by jcorteslinkare** [comment]
Hi Gary,

One more thing (for future reference). 

In production mode, as the only docker ports exposed to the physical server are 80 and 443, you can:

- If using a load balancer, SSL offload all traffic to port 80 of the physical host (certificates managed by load balancer);
- If not using a load balancer, redirect traffic to port 443 of the physical host (certificates managed by Nginx).

If using the second option, there are some tweaks that needs to be made at the nginx docker image.

**Comment by gpfconway** [comment]
Hi João,
I set up an SSL virtual host proxy off our main server using our certs (proxying to http):
https://elri.computing.dcu.ie/
Defaults to the main nginx page.
Nmap say that port 443 on our instance is not open:

Starting Nmap 6.47 ( http://nmap.org ) at 2019-01-22 17:04 GMT
Nmap scan report for elri-dev (136.206.217.121)
Host is up (0.00081s latency).
Not shown: 994 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
1025/tcp open  NFS-or-IIS
5432/tcp open  postgresql
8000/tcp open  http-alt
8080/tcp open  http-proxy

Nmap done: 1 IP address (1 host up) scanned in 1.61 seconds

**Comment by jcorteslinkare** [comment]
Hi Gary,

Port 443 is not opened at the current docker image configuration, can you redirect traffic to port 80 instead?

**Comment by gpfconway** [comment]
Hi João,
I will try Eva's suggestion to expose port 443 by editing the docker compose file and re-running the build.

**Comment by jcorteslinkare** [comment]
Hi all,

With the latest commit, SSL support is added to the nginx web server image:

- By default the server listens at port 443;
- By default the server creates a server.key and server.crt based on a dummy certificate created with the attributes: /C=PT/ST=Lisboa/L=Lisboa/O=Dev/CN=dev.elri-nrs.eu 
- For overriding the dummy certificate/key, you can map volumes to the certificate/key directories (check production environment configuration)

The documentation was also updated.

Any questions, feel free to ask.

**Comment by gpfconway** [comment]
Great!
I'll test that next week

**Comment by emartinezvic** [comment]
closed by a0161ad
