### ISSUE TITLE
Production NRS should enforce password validation

### ISSUE THREAD

**Issue by gpfconway** [ELDAELRA/ELRI#83]
Production NRS should enforce password validation to ensure use of strong passwords.
Can be enabled in Django:
https://docs.djangoproject.com/en/2.1/topics/auth/passwords/#module-django.contrib.auth.password_validation

**Comment by luismsgomes** [comment]
This functionality is available in Django 2.1 but not in Django 1.7 which is currently used by ELRI.
I may try to backport this functionality, but I'm not sure how much work that will involve.

**Comment by tetchegoyhen** [comment]
Ok, thanks Luis. If there's no easy backporting, I suggest we deprioritise this issue,

**Comment by luismsgomes** [comment]
Commit should 612fe7a fix this issue.

Most of the work that I did to fix this issue was backporting the django password validation from Django 1.9.  The code is available on pypi and github:

https://pypi.org/project/django-password-validation-backport/
https://github.com/luismsgomes/django-password-validation-backport

**Comment by emartinezvic** [comment]
Password is not checked against new user information in the register form
